#%RAML 1.0
title: Test

types:
  TestEntity:
    type: object
    properties:
      id: string
      name: string

/test-entity:
  get:
    responses:
      '200':
        body:
          application/json:
            type: TestEntity
    queryParameters:
      q1:
        required: false
        type: string
